version: '3'
services:
    web:
        container_name: "reser"
        image: ambientum/php:7.4-nginx
        ports:
            - "8080:8080"
        volumes:
            -  ".:/var/www/app"
        depends_on:
            - 'database'
        links:
            - 'database'

    database:
        container_name: "reser-database"
        platform: linux/x86_64
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: 'categ'
